### ISSUE TITLE
Automerge?

### ISSUE THREAD

**Issue by wshanks** [conda-forge/ibm-cloud-sdk-core-feedstock#23]
### Comment:

As a pure Python package with update-grayskull already enabled, this package might be a good candidate for automerge. What do you think? You all merge the updates pretty quickly any way, so not a big deal. I just noticed the last update blocked a downstream package (ibm-platform-services) from updating, so I thought I would ask. I use it on ibm-platform-services and it works well. The only thing to watch for is when dependencies are removed. update-grayskull will leave the unnecessary dependencies listed.

**Comment by BastianZim** [comment]
Agreed! Gonna leave this open for @synapticarbors to merge as a final ok but probably the easiest way.

**Comment by synapticarbors** [comment]
I've started adding the `update-grayskull` to many of the packages I maintain, but haven't turned on `automerge` in part because I don't fully trust everything to work exactly correctly. That said, I don't have a big vested interest in this particular package, so as long as @BastianZim is ok with cleaning up any mess that `automerging` might create, I'm fine with it.

**Comment by wshanks** [comment]
Okay, that's fair. For me so far, it has been worth the tradeoff on pure Python packages, but I do wish it would hold off on merging if dependencies were removed.

**Comment by BastianZim** [comment]
Yes, happy to clean it up – all good. @wshanks as you are maintaining the other IBM packages as well, feel free to add yourself here too.

> but I do wish it would hold off on merging if dependencies were removed.

Just a PR to the bot away... :)
